name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # o 'master' se usi ancora quel nome

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: website

      - name: Build Docusaurus site
        run: npm run build
        working-directory: website


      - name: Deploy to GitHub Pages
        run: |
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            GIT_USER=github-actions npm run deploy
        working-directory: website
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

